openapi: 3.0.0
info:
  title: Sandbox API
  version: 1.0.0
  description: API documentation for the Sandbox application.
servers:
  - url: http://localhost:8000/api/v1

paths:
  /healthcheck:
    get:
      summary: Used to check if the server is running.
      responses:
        '200':
          description: Server is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"

  /create_books:
    post:
      summary: Create a new book entry.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookInput'
      responses:
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'
  /delete_book/{id}:
    delete:
      summary: Delete a book by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the book to delete.
      responses:
        '200':
          description: Book deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteSuccessMessage'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
  /books:
    get:
      summary: Retrieve all books.
      responses:
        '200':
          description: List of books retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '500':
          $ref: '#/components/responses/InternalError'
  /books/{id}:
    get:
      summary: Retrieve a book by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the book to retrieve.
      responses:
        '200':
          description: Book retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          example: 1
        author:
          type: string
          example: "J.K. Rowling"
        title:
          type: string
          example: "Harry Potter and the Sorcerer's Stone"
        publisher:
          type: string
          example: "Bloomsbury"
        year:
          type: integer
          example: 1997
    BookInput:
      type: object
      required:
        - author
        - title
        - publisher
        - year
      properties:
        author:
          type: string
          example: "J.K. Rowling"
        title:
          type: string
          example: "Harry Potter and the Sorcerer's Stone"
        publisher:
          type: string
          example: "Bloomsbury"
        year:
          type: integer
          example: 1997
    SuccessMessage:
      type: object
      properties:
        message:
          type: string
          example: "book created successfully"
    DeleteSuccessMessage:
      type: object
      properties:
        message:
          type: string
          example: "book deleted successfully"
    ErrorMessage:
      type: object
      properties:
        error:
          type: string
          example: "error message"
  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          example:
            error: "invalid request body"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          example:
            error: "book not found"
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          example:
            error: "failed to process request"